<a href="https://colab.research.google.com/github/Soyeon20220610/githubTest/blob/main/tabular-playground-series-aug-2022/colab_reference.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# 시각화
import matplotlib.pyplot as plt
import matplotlib as mlp
import seaborn as sns

train=pd.read_csv('train.csv')
test= pd.read_csv('test.csv')

In [ ]:
train

id product_code  loading attribute_0 attribute_1  attribute_2  \
0          0            A    80.10  material_7  material_8            9   
1          1            A    84.89  material_7  material_8            9   
2          2            A    82.43  material_7  material_8            9   
3          3            A   101.07  material_7  material_8            9   
4          4            A   188.06  material_7  material_8            9   
...      ...          ...      ...         ...         ...          ...   
21182  21182            D   123.29  material_7  material_5            6   
21183  21183            D   134.15  material_7  material_5            6   
21184  21184            D    84.34  material_7  material_5            6   
21185  21185            D   102.17  material_7  material_5            6   
21186  21186            D   117.02  material_7  material_5            6   

       attribute_3  measurement_0  measurement_1  measurement_2  ...  \
0                5              7              8              4  ...   
1                5             14              3              3  ...   
2                5             12              1              5  ...   
3                5             13              2              6  ...   
4                5              9              2              8  ...   
...            ...            ...            ...            ...  ...   
21182            6              6              9              9  ...   
21183            6              8             12              8  ...   
21184            6              7              4              6  ...   
21185            6             16              5              4  ...   
21186            6              4              4              9  ...   

       measurement_9  measurement_10  measurement_11  measurement_12  \
0             10.672          15.859          17.594          15.193   
1             12.448          17.947          17.915          11.755   
2             12.715          15.607             NaN          13.798   
3             12.471          16.346          18.377          10.020   
4             10.337          17.082          19.932          12.428   
...              ...             ...             ...             ...   
21182         11.294          17.352          20.118          11.959   
21183         13.342          12.136          20.908           8.977   
21184         11.968          14.384          18.603          11.322   
21185         10.591          15.976          18.186          10.847   
21186         11.782          17.496          18.360             NaN   

       measurement_13  measurement_14  measurement_15  measurement_16  \
0              15.029             NaN          13.034          14.684   
1              14.732          15.425          14.395          15.631   
2              16.711          18.631          14.094          17.946   
3              15.250          15.562          16.154          17.172   
4              16.182          12.760          13.153          16.412   
...               ...             ...             ...             ...   
21182          15.339          16.763          14.652             NaN   
21183          16.445          15.888          14.181          17.134   
21184          15.832          15.992          14.296          16.787   
21185          16.166          15.841          15.626          16.909   
21186             NaN             NaN             NaN             NaN   

       measurement_17  failure  
0             764.100      0.0  
1             682.057      0.0  
2             663.376      0.0  
3             826.282      0.0  
4             579.885      0.0  
...               ...      ...  
21182             NaN      0.0  
21183         524.255      0.0  
21184         548.193      0.0  
21185         699.194      1.0  
21186             NaN      NaN  

[21187 rows x 26 columns]

In [ ]:
train['measurement_avg']=train[[f'measurement_{i}' for i in range(3,17)]].mean(axis=1)
test['measurement_avg']=test[[f'measurement_{i}' for i in range(3,17)]].mean(axis=1)

#data처리-1
# 안 쓰는 변수 제거 measurement_3~16
print('Before',train.shape,test.shape)

train=train.drop([ 'measurement_3', 'measurement_4', 'measurement_5',
       'measurement_6', 'measurement_7', 'measurement_8', 'measurement_9',
       'measurement_10', 'measurement_11', 'measurement_12', 'measurement_13',
       'measurement_14', 'measurement_15', 'measurement_16'],axis=1)

test=test.drop([ 'measurement_3', 'measurement_4', 'measurement_5',
       'measurement_6', 'measurement_7', 'measurement_8', 'measurement_9',
       'measurement_10', 'measurement_11', 'measurement_12', 'measurement_13',
       'measurement_14', 'measurement_15', 'measurement_16'],axis=1)


combine = [train,test]

print('After',train.shape,test.shape)

Before (21187, 27) (20775, 26)
After (21187, 13) (20775, 12)


In [ ]:
train

id product_code  loading attribute_0 attribute_1  attribute_2  \
0          0            A    80.10  material_7  material_8            9   
1          1            A    84.89  material_7  material_8            9   
2          2            A    82.43  material_7  material_8            9   
3          3            A   101.07  material_7  material_8            9   
4          4            A   188.06  material_7  material_8            9   
...      ...          ...      ...         ...         ...          ...   
21182  21182            D   123.29  material_7  material_5            6   
21183  21183            D   134.15  material_7  material_5            6   
21184  21184            D    84.34  material_7  material_5            6   
21185  21185            D   102.17  material_7  material_5            6   
21186  21186            D   117.02  material_7  material_5            6   

       attribute_3  measurement_0  measurement_1  measurement_2  \
0                5              7              8              4   
1                5             14              3              3   
2                5             12              1              5   
3                5             13              2              6   
4                5              9              2              8   
...            ...            ...            ...            ...   
21182            6              6              9              9   
21183            6              8             12              8   
21184            6              7              4              6   
21185            6             16              5              4   
21186            6              4              4              9   

       measurement_17  failure  measurement_avg  
0             764.100      0.0        15.350538  
1             682.057      0.0        15.446286  
2             663.376      0.0        15.784231  
3             826.282      0.0        15.599500  
4             579.885      0.0        15.194071  
...               ...      ...              ...  
21182             NaN      0.0        15.728231  
21183         524.255      0.0        14.986385  
21184         548.193      0.0        15.088786  
21185         699.194      1.0        15.366500  
21186             NaN      NaN        15.593625  

[21187 rows x 13 columns]

In [ ]:
# product_code, attribute_0, attribute_1 를 숫자로 바꿈

# product_code 을숫자로 바꿈
for dataset in [train,test]:
    dataset['product_code']=dataset['product_code'].map({'A':1,'B':2,'C':3,'D':4,'E':5,'F':6,'G':7,'H':8,'I':9}).astype(int)


for dataset in [train,test]:
    dataset['attribute_0']=dataset['attribute_0'].map({'material_7':2,'material_5':1}).astype(int)

for dataset in [train,test]:
    dataset['attribute_1']=dataset['attribute_1'].map({'material_5':1,'material_6':2,'material_7':3,'material_8':4}).astype(int)


In [ ]:
test

id  product_code  loading  attribute_0  attribute_1  attribute_2  \
0      26570             6   119.57            1            2            6   
1      26571             6   113.51            1            2            6   
2      26572             6   112.16            1            2            6   
3      26573             6   112.72            1            2            6   
4      26574             6   208.00            1            2            6   
...      ...           ...      ...          ...          ...          ...   
20770  47340             9   144.74            2            1            9   
20771  47341             9    74.53            2            1            9   
20772  47342             9    67.73            2            1            9   
20773  47343             9   126.15            2            1            9   
20774  47344             9    85.97            2            1            9   

       attribute_3  measurement_0  measurement_1  measurement_2  \
0                4              6              9              6   
1                4             11              8              0   
2                4              8             12              4   
3                4              8             11             10   
4                4             14             16              8   
...            ...            ...            ...            ...   
20770            5              0              4              9   
20771            5              4              8              7   
20772            5             10             11              2   
20773            5              8             16             11   
20774            5              0             11             11   

       measurement_17  measurement_avg  
0             634.612        15.423286  
1             537.037        15.013462  
2             658.995        15.259429  
3             594.301        14.892357  
4             801.044        15.430714  
...               ...              ...  
20770         696.466        15.554750  
20771         613.249        14.932000  
20772         783.349        16.060385  
20773         745.210        15.512000  
20774         647.980        15.582714  

[20775 rows x 12 columns]

In [ ]:
train.isnull().sum(), test.isnull().sum()

(id                    0
 product_code          0
 loading             188
 attribute_0           0
 attribute_1           0
 attribute_2           0
 attribute_3           0
 measurement_0         0
 measurement_1         0
 measurement_2         0
 measurement_17     1807
 failure               1
 measurement_avg       0
 dtype: int64, id                    0
 product_code          0
 loading             223
 attribute_0           0
 attribute_1           0
 attribute_2           0
 attribute_3           0
 measurement_0         0
 measurement_1         0
 measurement_2         0
 measurement_17     1740
 measurement_avg       0
 dtype: int64)

In [ ]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer( strategy='most_frequent') #'median'을 쓰면 중앙값사용
imp_mean.fit(train)
train_imputed = pd.DataFrame(imp_mean.transform(train))
imp_mean = SimpleImputer( strategy='most_frequent') #'median'을 쓰면 중앙값사용
imp_mean.fit(test)
test_imputed = pd.DataFrame(imp_mean.transform(test))

In [ ]:
# !pip install impyute

In [ ]:
# # KNN 으로 null 채우기 - train
# from impyute.imputation.cs import fast_knn
# np_imputed=fast_knn(train.values, k=5)# KNN 학습 
# train_imputed = pd.DataFrame(np_imputed)
# np_imputed=fast_knn(test.values, k=5)# KNN 학습 
# test_imputed = pd.DataFrame(np_imputed)


In [ ]:
train_imputed.isnull().sum(), test_imputed.isnull().sum()

(0     0
 1     0
 2     0
 3     0
 4     0
 5     0
 6     0
 7     0
 8     0
 9     0
 10    0
 11    0
 12    0
 dtype: int64, 0     0
 1     0
 2     0
 3     0
 4     0
 5     0
 6     0
 7     0
 8     0
 9     0
 10    0
 11    0
 dtype: int64)

In [ ]:
train_imputed

0    1       2    3    4    5    6     7     8    9        10  \
0          0.0  1.0   80.10  2.0  4.0  9.0  5.0   7.0   8.0  4.0  764.100   
1          1.0  1.0   84.89  2.0  4.0  9.0  5.0  14.0   3.0  3.0  682.057   
2          2.0  1.0   82.43  2.0  4.0  9.0  5.0  12.0   1.0  5.0  663.376   
3          3.0  1.0  101.07  2.0  4.0  9.0  5.0  13.0   2.0  6.0  826.282   
4          4.0  1.0  188.06  2.0  4.0  9.0  5.0   9.0   2.0  8.0  579.885   
...        ...  ...     ...  ...  ...  ...  ...   ...   ...  ...      ...   
21182  21182.0  4.0  123.29  2.0  1.0  6.0  6.0   6.0   9.0  9.0  558.345   
21183  21183.0  4.0  134.15  2.0  1.0  6.0  6.0   8.0  12.0  8.0  524.255   
21184  21184.0  4.0   84.34  2.0  1.0  6.0  6.0   7.0   4.0  6.0  548.193   
21185  21185.0  4.0  102.17  2.0  1.0  6.0  6.0  16.0   5.0  4.0  699.194   
21186  21186.0  4.0  117.02  2.0  1.0  6.0  6.0   4.0   4.0  9.0  558.345   

        11         12  
0      0.0  15.350538  
1      0.0  15.446286  
2      0.0  15.784231  
3      0.0  15.599500  
4      0.0  15.194071  
...    ...        ...  
21182  0.0  15.728231  
21183  0.0  14.986385  
21184  0.0  15.088786  
21185  1.0  15.366500  
21186  0.0  15.593625  

[21187 rows x 13 columns]

In [ ]:
for a in range(13):
    b=['id', 'product_code', 'loading', 'attribute_0', 'attribute_1',
       'attribute_2', 'attribute_3', 'measurement_0', 'measurement_1',
       'measurement_2', 'measurement_17', 'failure', 'measurement_avg']
    train_imputed.rename(columns={a:b[a]},inplace=True)
for a in range(12):
    b= ['id', 'product_code', 'loading', 'attribute_0', 'attribute_1',
       'attribute_2', 'attribute_3', 'measurement_0', 'measurement_1',
       'measurement_2', 'measurement_17','measurement_avg']
    test_imputed.rename(columns={a:b[a]},inplace=True)

# failure, measurement_avg order change
train_imputed = train_imputed[['id', 'product_code', 'loading', 'attribute_0', 'attribute_1',
       'attribute_2', 'attribute_3', 'measurement_0', 'measurement_1',
       'measurement_2', 'measurement_17', 'measurement_avg','failure' ]]


In [ ]:
train_imputed

id  product_code  loading  attribute_0  attribute_1  attribute_2  \
0          0.0           1.0    80.10          2.0          4.0          9.0   
1          1.0           1.0    84.89          2.0          4.0          9.0   
2          2.0           1.0    82.43          2.0          4.0          9.0   
3          3.0           1.0   101.07          2.0          4.0          9.0   
4          4.0           1.0   188.06          2.0          4.0          9.0   
...        ...           ...      ...          ...          ...          ...   
21182  21182.0           4.0   123.29          2.0          1.0          6.0   
21183  21183.0           4.0   134.15          2.0          1.0          6.0   
21184  21184.0           4.0    84.34          2.0          1.0          6.0   
21185  21185.0           4.0   102.17          2.0          1.0          6.0   
21186  21186.0           4.0   117.02          2.0          1.0          6.0   

       attribute_3  measurement_0  measurement_1  measurement_2  \
0              5.0            7.0            8.0            4.0   
1              5.0           14.0            3.0            3.0   
2              5.0           12.0            1.0            5.0   
3              5.0           13.0            2.0            6.0   
4              5.0            9.0            2.0            8.0   
...            ...            ...            ...            ...   
21182          6.0            6.0            9.0            9.0   
21183          6.0            8.0           12.0            8.0   
21184          6.0            7.0            4.0            6.0   
21185          6.0           16.0            5.0            4.0   
21186          6.0            4.0            4.0            9.0   

       measurement_17  measurement_avg  failure  
0             764.100        15.350538      0.0  
1             682.057        15.446286      0.0  
2             663.376        15.784231      0.0  
3             826.282        15.599500      0.0  
4             579.885        15.194071      0.0  
...               ...              ...      ...  
21182         558.345        15.728231      0.0  
21183         524.255        14.986385      0.0  
21184         548.193        15.088786      0.0  
21185         699.194        15.366500      1.0  
21186         558.345        15.593625      0.0  

[21187 rows x 13 columns]

In [ ]:
X_train=train_imputed.drop(['failure'],axis=1)
Y_train=train_imputed['failure']

X_test=test_imputed.copy()

In [ ]:
Y_train

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
21182    0.0
21183    0.0
21184    0.0
21185    1.0
21186    0.0
Name: failure, Length: 21187, dtype: float64

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# normalization
from sklearn import preprocessing
X_train = preprocessing.normalize(X_train, axis=0)
X_test = preprocessing.normalize(X_test, axis=0)

In [ ]:
X_train

array([[0.00000000e+00, 2.50676958e-03, 4.12456513e-03, ...,
        3.80817866e-03, 7.50591374e-03, 6.81256935e-03],
       [5.61657809e-07, 2.50676958e-03, 4.37121516e-03, ...,
        2.85613400e-03, 6.69998823e-03, 6.85506198e-03],
       [1.12331562e-06, 2.50676958e-03, 4.24454312e-03, ...,
        4.76022333e-03, 6.51648087e-03, 7.00504200e-03],
       ...,
       [1.18981590e-02, 1.00270783e-02, 4.34289417e-03, ...,
        5.71226800e-03, 5.38501423e-03, 6.69640347e-03],
       [1.18987207e-02, 1.00270783e-02, 5.26100898e-03, ...,
        3.80817866e-03, 6.86832856e-03, 6.81965308e-03],
       [1.18992823e-02, 1.00270783e-02, 6.02567555e-03, ...,
        8.56840199e-03, 5.48473944e-03, 6.92045116e-03]])

In [ ]:
X_train.shape, Y_train.shape,X_test.shape

((21187, 12), (21187,), (20775, 12))

In [ ]:
from sklearn.linear_model import LogisticRegression

#logistic regression
logreg=LogisticRegression()
logreg.fit(X_train,Y_train)
Y_pred_LR = logreg.predict(X_test)
acc_log = round(logreg.score(X_train,Y_train)*100,2)
acc_log, np.unique(Y_pred_LR)

(78.6, array([0.]))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
# Random Forest

random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, Y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_train, Y_train)
acc_random_forest = round(random_forest.score(X_train, Y_train) * 100, 2)
acc_random_forest
Y_pred.shape

(20775,)

In [ ]:
acc_random_forest


100.0

In [ ]:
np.unique(Y_pred)

array([0., 1.])

In [ ]:
# Decision Tree
from sklearn.ensemble import RandomForestClassifier

decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, Y_train)
Y_pred = decision_tree.predict(X_test)
acc_decision_tree = round(decision_tree.score(X_train, Y_train) * 100, 2)
acc_decision_tree

100.0

In [ ]:
np.unique(Y_pred)

array([0., 1.])

In [ ]:
# sample_sumbmission=pd.read_csv('sample_submission.csv')

submission = pd.DataFrame({
        "Id" : np.arange(26570,47345),
        "failure": Y_pred
    })

submission.to_csv("submission.csv", index = False)

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, Y_train)
Y_pred_knn = knn.predict(X_test)
acc_knn = round(knn.score(X_train, Y_train) * 100, 2)
print(acc_knn)
np.unique(Y_pred_knn)

83.01


array([0., 1.])